name: ci-linter

on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: true
        description: Version of .NET to use (e.g., 8.0.x)
        
permissions:
  contents: read
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ inputs.dotnet-version }}

      - name: Run Husky
        run: |
          dotnet tool restore && \
          dotnet husky install && \
          dotnet husky run -g "lint"
  