name: ci-shotcaller
concurrency: ci-shotcaller

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:    
  pull_request:
    branches:
      - main
  push:
    paths:
      - src
      - .github

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/linter.yml
    with:
      dotnet-version: 8.0.x
  restorebuildtest:
    name: Restore, Build, and Test
    needs:
      - lint
    uses: ./.github/workflows/restore-build-test.yml
    with:
      dotnet-version: 8.0.x
      test-project-names: '["ShotCaller.Azure.ServiceBus.Messaging.Tests"]'
    secrets: 
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
      

  