name: ci-shotcaller
concurrency: ci-shotcaller

on:
  pull_request: 
    branches:
      - main
  push: 
    paths:
      - src
      - .github

jobs: 
  checklist:
    name: checklist
    uses: ./.github/workflows/ci-checklist.yml
    with:
      project-path: tests/ShotCaller.Azure.ServiceBus.Messaging.Tests/ShotCaller.Azure.ServiceBus.Messaging.Tests.csproj
      

  