name: ci-shotcaller
concurrency: ci-shotcaller

on:
  push: 
    paths:
      - src
      - .github

jobs: 
  checklist:
    name: checklist
    uses: ./.github/workflows/ci-checklist.yml
    with:
      project-path: src/ShotCaller.Azure.ServiceBus.Messaging/ShotCaller.Azure.ServiceBus.Messaging.csproj
      

  