name: ci-shotcaller
concurrency: ci-shotcaller

on:
  pull_request: 
    branches:
      - main
  push: 
    paths:
      - src
      - .github

jobs: 
  lint:
    name: Lint
    uses: ./.github/workflows/ci-linter.yml
    with:
      dotnet-version: 8.0.x      
      

  